### ISSUE TITLE
It's looking for whisper 0.3.0?

### ISSUE THREAD

**Issue by tholonia** [VideotronicMaker/LM-Studio-Voice-Conversation#2]
```
 pip install -r requirements.txt
Collecting keyboard==0.13.5 (from -r requirements.txt (line 1))
  Using cached keyboard-0.13.5-py3-none-any.whl.metadata (4.0 kB)
Collecting openai==0.27.0 (from -r requirements.txt (line 2))
  Using cached openai-0.27.0-py3-none-any.whl.metadata (13 kB)
Collecting pyaudio==0.2.11 (from -r requirements.txt (line 3))
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
  Preparing metadata (setup.py) ... done
Collecting pyttsx3==2.90 (from -r requirements.txt (line 4))
  Using cached pyttsx3-2.90-py3-none-any.whl.metadata (3.6 kB)
Collecting tk==0.1.0 (from -r requirements.txt (line 5))
  Using cached tk-0.1.0-py3-none-any.whl.metadata (693 bytes)
ERROR: Could not find a version that satisfies the requirement whisper==0.3.0 (from versions: 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.16, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10)
ERROR: No matching distribution found for whisper==0.3.0
```

**Comment by VideotronicMaker** [comment]
You could try updating the requirements.txt file to this:

keyboard==0.13.5
openai==0.27.0
pyaudio==0.2.11
pyttsx3==2.90
tk==0.1.0
whisper==v20231117

or

Choose one of these versions from the error message:

ERROR: Could not find a version that satisfies the requirement whisper==0.3.0 (from versions: 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 0.9.11, 0.9.12, 0.9.13, 0.9.14, 0.9.15, 0.9.16, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10)

Example:

keyboard==0.13.5
openai==0.27.0
pyaudio==0.2.11
pyttsx3==2.90
tk==0.1.0
whisper==1.1.10


Here is a link to the GitHub Repo for Whisper with their releases.  
https://github.com/openai/whisper/releases
